baseURL = "/"
title = "Gree® Labs"
theme = "hugo-bearblog"
locale = "id"

[params]
  author = "Gree® Labs"
  description = "Inovasi Teknologi Pendingin Udara, Air Treatment, dan Rekayasa Tata Udara"
  dateFormat = "02 Jan, 2006"

[menu]
  [[menu.main]]
    name = "Beranda"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Katalog"
    url = "/blog/"
    weight = 2

  [[menu.main]]
    name = "Tentang"
    url = "/tentang-kami/"
    weight = 3

  [[menu.main]]
    name = "Kontak"
    url = "/kontak/"
    weight = 4