baseURL = "https://greelabs.pages.dev/"
languageCode = "id"
title = "Gree® Labs"
theme = "hugo-bearblog"

[params]
author = "Gree® Labs"
description = "Pusat inovasi teknologi, riset pendingin udara, dan solusi resmi Gree Indonesia."
title = "Gree® Labs"
favicon = ""

[menu]
[[menu.main]]
name = "Beranda"
url = "/"
weight = 1

[[menu.main]]
name = "Katalog & Riset"
url = "/blog/"
weight = 2

[[menu.main]]
name = "Tentang Gree® Labs"
url = "/tentang-kami/"
weight = 3

[[menu.main]]
name = "Kontak & Dukungan"
url = "/kontak/"
weight = 4
